### ISSUE TITLE
Taken official name from App.Metrics

### ISSUE THREAD

**Issue by humble-race-condition** [alex-kabin/AK.App.Metrics.Reporting.InfluxDB2#1]
Hello. The official developer for App.Metrics created the support for InfluxDB2. Unfortunately, the name is taken by you. Could you, please, check this thread https://github.com/AppMetrics/AppMetrics/pull/701 and free up the name in nuget, or communicate with the contributors from App.Metrics so that we can get this going.

Thank you in advance :) !

**Comment by alex-kabin** [comment]
Hi! Sorry, for name collision, i did not think in advance) I've unlisted and deprecated my package at nuget, hope this will free up official name.

**Comment by humble-race-condition** [comment]
Thank you very much for the fast response :) !!! I wish you have great Holidays and new year welcoming :) !
