### ISSUE TITLE
InfluxDb2.InfluxDbMetricsReporter FlushAsync failed

### ISSUE THREAD

**Issue by krzysiek-b** [alex-kabin/AK.App.Metrics.Reporting.InfluxDB2#2]
Seems this does not work with InfluxDB 2.1.1. Does the package support latest InfluxDB?

```
[10:38:06 ERR] Failed to write to InfluxDB - Status: 400 (Bad Request)
[10:38:06 WRN] Reporter App.Metrics.Reporting.InfluxDb2.InfluxDbMetricsReporter FlushAsync failed
```

**Comment by mlapaglia** [comment]
same problem, any insight?

**Comment by alex-kabin** [comment]
Tested with InfluxDB 2.5 and everything worked ok.
Nevertheless, updated to version 4.3.0, enriched error logging, added test project.
And please, check your setting "BaseUri": "http://localhost:8086/api/v2/" - make sure url ends with **/api/v2/**

**Comment by mlapaglia** [comment]
i ran the docker version influxdb 2.5.1 instead of the ubuntu package version and it started working correctly. not sure why but thank you for your help!

**Comment by alex-kabin** [comment]
works on InfluxDB 2.5+
