### ISSUE TITLE
Targeting .NET Standard 2.0

### ISSUE THREAD

**Issue by mlapaglia** [alex-kabin/AK.App.Metrics.Reporting.InfluxDB2#3]
Can this target .NET Standard 2.0 to align with the base AppMetrics library? 2.1 can't be used in .NET 4.8.
https://www.nuget.org/packages/App.Metrics/

**Comment by mlapaglia** [comment]
here's a pr showing the changes needed https://github.com/alex-kabin/AK.App.Metrics.Reporting.InfluxDB2/pull/4

**Comment by alex-kabin** [comment]
implemented in v4.3.1
